### ISSUE TITLE
Ember: How to get sign-in form on page load

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/capstone-project#120]
Is there an ember-y way to have the sign-in form load on page load, rather than making the user click the sign-in link?

**Comment by jrhorn424** [comment]
@MFBrewster and I discussed this briefly. I recommended using the `activate` hook, which fires after other hooks on the model have completed successfully. The idea is to use the auth service to check if a user is authenticated, and if they are not, transition immediately to the sign-in page.

**Comment by MFBrewster** [comment]
I included 

``` js
activate () {
    if (!isAuthenticated) {
      this.transitionTo('sign-in');
    }
  },
```

in my application router, and on page load the page was totally blank. I'm moving on without this feature for now, but further guidance would be appreciated.

**Comment by jrhorn424** [comment]
What was the error in the console, if any?

**Comment by jrhorn424** [comment]
Perhaps this?

``` diff
-    if (!isAuthenticated) {
+    if (Ember.computed.not('isAuthenticated')) {
```

**Comment by faetea** [comment]
From a user experience standpoint tho, are you 100% that you don't want to have any content that is Public?  When you are demoing the app for someone or they are looking at your code on github, then it's fine for it to all require authentication.  But if you are sending out a portfolio link and you want a stranger or acquaintance to test your app, it might be good to at least have one page they can access without creating an account, so that they know why they want to make an account.

**Comment by MFBrewster** [comment]
Fixed this issue with Matt's help, but not without creating one other minor issue: https://github.com/ga-wdi-boston/capstone-project/issues/123

Allie's UI concern is noted, and that's a problem I'll wrestle with later in the app's development. Closing this issue.
