### ISSUE TITLE
Relational Mapping

### ISSUE THREAD

**Issue by tina513** [ga-wdi-boston/capstone-project#204]
Hey guys,

I have a question regarding of my database structure. Please help~
My app is a recipe website user create many recipes, and users can subscribe to many recipes. I add reference user_id to my recipe table and also create a join table "subscription" for users and recipes; But every time when I create a recipe by current_user,  user_id column inside recipe table is empty, and subscription join table for user_id and recipe_id are populated. I want user_id column populate inside recipe table, but not the join table gets populating for creating new recipes.

psql for recipe table:

```
    rails-api-template_development=# select * from recipes;
 id |         name          | category |     instructions      | user_id |         created_at         |         updated_at         
----+-----------------------+----------+-----------------------+---------+----------------------------+----------------------------
  3 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 17:56:04.454087 | 2016-07-30 17:56:04.454087
  4 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 18:12:11.764662 | 2016-07-30 18:12:11.764662
  5 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 18:13:18.895737 | 2016-07-30 18:13:18.895737
  7 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 18:17:10.664165 | 2016-07-30 18:17:10.664165
  8 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 19:23:35.388512 | 2016-07-30 19:23:35.388512
  9 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 19:30:40.749189 | 2016-07-30 19:30:40.749189
 10 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 19:30:49.670692 | 2016-07-30 19:30:49.670692
 11 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 19:34:37.86985  | 2016-07-30 19:34:37.86985
 12 | an example recipe     | fry      | {"do it","ignore it"} |         | 2016-07-30 19:36:02.02072  | 2016-07-30 19:36:02.02072
  1 | second example recipe | grill    | {"do it","ignore it"} |         | 2016-07-30 17:24:09.475124 | 2016-07-30 19:53:09.676555
```

psql for subscription join table:

```
     id | recipe_id | user_id |         created_at         |         updated_at         
----+-----------+---------+----------------------------+----------------------------
  1 |         1 |       1 | 2016-07-30 17:24:09.501608 | 2016-07-30 17:24:09.501608
  3 |         3 |       1 | 2016-07-30 17:56:04.475912 | 2016-07-30 17:56:04.475912
  4 |         4 |       1 | 2016-07-30 18:12:11.773793 | 2016-07-30 18:12:11.773793
  5 |         5 |       1 | 2016-07-30 18:13:18.913938 | 2016-07-30 18:13:18.913938
  6 |         7 |       1 | 2016-07-30 18:17:10.674524 | 2016-07-30 18:17:10.674524
  7 |         8 |       1 | 2016-07-30 19:23:35.424875 | 2016-07-30 19:23:35.424875
  8 |         9 |       1 | 2016-07-30 19:30:40.78174  | 2016-07-30 19:30:40.78174
  9 |        10 |       1 | 2016-07-30 19:30:49.680114 | 2016-07-30 19:30:49.680114
 10 |        11 |       1 | 2016-07-30 19:34:37.921801 | 2016-07-30 19:34:37.921801
 11 |        12 |       1 | 2016-07-30 19:36:02.034449 | 2016-07-30 19:36:02.034449
```

Please let me know how to build correct relation mapping for my database~

**Comment by jrhorn424** [comment]
I reviewed @tina513's ERD. Currently there are a few drawbacks:
- While debugging a relational issue, she created a profiles table which allowed her to get a user_id associated with a recipe. I haven't fully diagnosed this issue, and as it is a concatenation of issues previously debugged, I've asked her to go back to the modeling that originally led to the problem before we continue. This isn't a loss, since profiles only existed to address the previous issue, and contained no data itself.
- There's an unnecessary normalization applied by moving "recipe ingredients" from recipes into its own table. While its true that we teach developers not to store arrays in columns, in this case Tina convinced me she had no reason to have a single, canonical entry for, say, "egg" or "butter". In fact, each ingredient named "egg" would potentially be entered multiple times for different recipes since "amount" was also included as an attribute of a recipe_ingredient. @berziiii suggested inlining the ingredients into the recipes table and I concur.

@berziiii please add notes to these issues in the future as you help developers model their projects. Thanks.

**Comment by tina513** [comment]
I go back to my previous model, which don't have profile and separate recipe_ingredients table. There is some weird issue in my model files, and after several roll back migrations. Every thing worked. I will double check my database structure(relational mapping) before I make too much changes to the file. Thanks for everyone's help~  @jrhorn424 @berziiii
