### ISSUE TITLE
Trouble Defining Component w/ Ember

### ISSUE THREAD

**Issue by RoobScoobs** [ga-wdi-boston/capstone-project#216]
Hey guys, 

I'm having trouble defining my components. I want to have a form for creating a new album but not sure where it belongs in my app directory. So far I have a button in the index page (where albums from every user is displayed - /albums) that will take you to a new route (/albums/create) and in this view I want to render the template that houses the form and the action for a submission. 

Because it's a form I know it should be defined as a component given the list example but I guess I'm getting confused with the structure and how the data binding works here.

**Comment by berziiii** [comment]
If you are going to be using the inputs again, say in an update album form, then each input should be its own component. Which is called by the 'create-album-form'. You won't have data going down yet since it's a create form, but you need to set variables for the input values and set action bindings from top level down. See my 'create-book' form set up for further assistance https://github.com/berziiii/library-client/tree/master/app . Happy to guide when I get in.

**Comment by RoobScoobs** [comment]
Great! This helps a lot. I'll turn each input into its own component since it can be reused for updating as well.

**Comment by payne-chris-r** [comment]
Scoops, can you close this if it's resolved?
