### ISSUE TITLE
Ember posting requests even with stored data

### ISSUE THREAD

**Issue by lcurran** [ga-wdi-boston/capstone-project#219]
When I click back and forth between my games index and my libraries index, or any other element of my app, it issues a GET each time I click on each one even if the data is already in the store.

Below was from me clicking between games index and change password:
<img width="511" alt="screen shot 2016-08-02 at 9 32 25 am" src="https://cloud.githubusercontent.com/assets/15129578/17330159/b59be6da-5893-11e6-8306-86757275747f.png">

**Comment by jrhorn424** [comment]
`findAll` always busts the cache.

**Comment by lcurran** [comment]
should i use:
```
    return this.get('store').query('library');
```
instead?

**Comment by lcurran** [comment]
is there a better alternative?

**Comment by jrhorn424** [comment]
I don't think so, unless you have a custom route for singular resource.

**Comment by berziiii** [comment]
Worked with Lindsey and we were able to resolve the api and ember side modeling issues. The key was to ensure that her api was referencing the join table correctly first. Then in the serializers for both of the models being joined through the join table, we had to add custom methods. 

For example:

# join table serializer

``` ruby
attributes :id, :user_id, :game_id, :game, :user

def user
   object.user.id
end

def game
   object.game.id
end
```

# game serializer

``` ruby
attributes :id, :libraries, :users

def libraries
   object.libraries.pluck(:id)
end

def users
   object.users.pluck(:id)
end
```

same for users but replacing all `users` to `games`

The reason for this is due to what ember wants. Ember likes having access to ID's and when you have several things it needs to do a get for, if ember has the id, it will successfully get it. You MUST have associated model.js and route.js files for the corresponding models in Ember.

**Comment by jrhorn424** [comment]
The alternative to changing the API serializer is to change the client serializer. But yes, it does have to change somewhere.
