### ISSUE TITLE
1 on 1 request to discuss ember structure for my project

### ISSUE THREAD

**Issue by rosmith76** [ga-wdi-boston/capstone-project#297]
I am a little confused on the structure I need in ember for my project. I have been looking at the lessons we did last week as a guide, and I still confused. The basic data structure for my app is as follows.
User will have one or many bikes. Each bike is made up of 27 parts. I used to following command to set up my API.
```
rails g scaffold Bikes name:string date_of_purchase:date make:string frame:string fork:string fork_service:string brakes:string brake_bleed:date pad_replaced:date rotors:string wheels:string tires:string sealant:date shifters:string front_derailleur:string rear_derailleur:string cassette:string chain:string cranks:string bottom_bracket:string saddle:string seatpost:string stem:string handlebars:string grips:string headset:string notes:string
```
Will I need a component for each part, or will they all exist under bike?

**Comment by jrhorn424** [comment]
> Will I need a component for each part, or will they all exist under bike?

In order to answer the question of components, we need a wireframe. What are your screens going to look like?

**Comment by rosmith76** [comment]
I have basic wireframes. I can give more details if needed.
Single page App with various view states
Landing page wireframe https://wireframe.cc/UhvNk3
Create new bike wireframe https://wireframe.cc/Gcxgno
View bikes wireframe https://wireframe.cc/rnLFmu
View bike wireframe https://wireframe.cc/gT43sB stretch goal to include image uploading.

**Comment by jrhorn424** [comment]
Thanks! Let's meet tomorrow to go over identifying components.

**Comment by rosmith76** [comment]
Thanks. Let me know what time is best.

**Comment by jrhorn424** [comment]
@rosmith76 and I had a great conversation. I'm seeing a lot of progress.

There were a few notes that might help others:
-   The error hook in the application route was swallowing an error. After removing the error hook, the error from Ember came through and told us that:
-   @rosmith76 had accidentally used `bikes` instead of `bike` as the first argument to `findAll` in the `bikes` route handler. Fixing that allowed us to see the expected data.
-   We added a links from the `bikes` route template to each individual `bike` route using `each` and passing the individual `bike` as the second argument to `link-to`.
-   We bound the bike data down to a `my-bike` component and got that component to render some information.

@rosmith76 was unaware that components had to have two words in them. I hope this helps someone else experiencing difficult with naming components!
