### ISSUE TITLE
[Ember] 1on1 request: components & actions & structuring code in app

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/capstone-project#305]
I have two components that I'm reusing throughout my app, in other components and in different routes. For example: a "favorite this!" button that's visible at `/patterns`, at `/patterns/:pattern_id` (the `pattern` route), when viewing an individual project based on that pattern (at `/projects/:project_id`), when viewing the user's list of favorites (`favorites`), and in other places. 

I'm starting to repeat code for these components' actions across different routes (`pattern`, `patterns`, `favorites`, etc.), which seems less than ideal / prone to errors.

I'd like to meet with someone for a few minutes to a) double check my understanding of how actions work / are connected across components and routes; and b) see if there's a way to reduce some of the repetition I'm experiencing.

**Comment by jrhorn424** [comment]
@rhjones I'll meet with you in the morning. If I understand your use-case correctly, some duplication may be necessary. Maybe we can come up with some heuristics to record here after looking at your code.

**Comment by jrhorn424** [comment]
After discussing some options, we decided to go with injecting the store into the component to do the CRUD on the favorites join. Arguments for doing it this way:
1.  The CRUD is linked to "toggling" a join property (favorite) with a primary property (pattern). The "toggling" happens by deleting a row or adding a row as appropriate to the favorites table.
2.  Because the component is re-used in approx. 4 routes across two different containing components, it felt more like a service concern (tempted to create a service), but since it was a service provided by an internal API that already had a front-end model, we opted to inject the store.
3.  It's possible there are better component architectures. The components seemed well-abstracted pieces of encapsulated UI.
4.  We did not explore closure actions
