### ISSUE TITLE
One-on-one request for modeling

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/capstone-project#316]
Hello!

I'd like to have the opportunity to share my progress with you and talk about my project modeling.

Thank you,
Violeta

**Comment by jrhorn424** [comment]
Links to ERDs, wireframes, and use stories, please.

**Comment by viohlet** [comment]
Sorry about that. Please see this link: https://docs.google.com/document/d/1nSy7w2vs47iIfxVnmcTnxFRsi0RS_MawEy83Z_hd8x4/edit?usp=sharing

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core Who can meet with Violeta this afternoon?

**Comment by jrhorn424** [comment]
@viohlet If you have specific questions, I'm happy to answer them through the tracker. For example "I made this decision because of X, but now I'm thinking about Y, what's the best approach?" or "These were my goals in modeling, but now I'm not sure anymore because X, Y, Z. What's your opinion?"

With more details I can respond with my opinions or with questions if needed.

**Comment by payne-chris-r** [comment]
I can meet with @viohlet at 4 (if not before)

**Comment by viohlet** [comment]
Thanks for meeting with me @payne-chris-r. Will make sure to post in the tracker if I have any specific issues, @jrhorn424. Thank you!
