### ISSUE TITLE
[Ember] Computed Properties.  Is there a way to do the opposite of FilterBy?

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/capstone-project#340]
I have a property which I would like to do the opposite of a filterby.( ) on.
The code below in the navItems property appears to take my property portfolioItems (an array-like) and remove every element that has the 'artform' of 'parent' (parent here has been passed down as 'visual'). 

I would instead like to keep all of the elements that have the 'artform' of 'parent' rather than throwing them away, but I cannot find a function with that signature in the Computed Properties API.

```js
export default Ember.Component.extend({
  portfolioItems: Ember.computed.uniqBy('items', 'portfolio'),
  navItems: Ember.computed.filterBy('portfolioItems', 'artform', 'parent')
});
```

**Comment by DanielJRaine** [comment]
Closing because bigger fish to fry, and this hasn't gotten attention.

**Comment by jrhorn424** [comment]
I was literally typing a response.

**Comment by jrhorn424** [comment]
The issue turned out to be that the `signOut` action clears the store.

That's a problem for this use case, and broader use cases in the app. Authentication is not required to see things, only to edit them, so clearing the store was harmful.

If we want to only clear `user` data, that's fine. But we don't often see folks actually using `user` model instances in their app. What actually needs to be done is clearing local storage, which we already take care of inside the auth service.
