### ISSUE TITLE
store.query and store.filter are returning everything, not filtering out anything.

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/capstone-project#341]
same problem I had before, different implementation.  still not working.
```js
  model() {
    return this.get('store').filter('item', function(item){
       if (item.get('section') === 'musician-portraits') {
         return item;
       }
    });
  },
```

**Comment by DanielJRaine** [comment]
![Undertale](http://pre04.deviantart.net/3474/th/pre/f/2016/009/5/d/but_nobody_came_5___undertale_by_dragonitearmy-d9nc9gc.png)

**Comment by payne-chris-r** [comment]
^ is this a comment on the fact that you haven't received a response yet?

**Comment by jrhorn424** [comment]
`DS.Store.filter` has been deprecated since 1.13.

Daniel mentioned trying the following anecdotally, but I didn't see it, so I could be reproducing it wrong:

``` js
  model() {
    return this.get('store').findAll('item')
      .filterBy('section', 'musician-portraits');
  },
```

But `findAll` returns a Promise.

For want of a `then`...

 We also spent time confirming what methods were available by looking into the resolved value's prototype, which was `Ember.RecordArray`. This type extends from `Ember.ArrayProxy`, which does indeed have a `filterBy` method that works (but don't forget to return the values!).

``` js
  model() {
    return this.get('store').findAll('item')
      .then((items) => {
        return items.filterBy('section', 'musician-portraits');
      })
      ;
    });
  },
```

**Comment by jrhorn424** [comment]
@DanielJRaine Please close when you get a moment. Thanks.

**Comment by DanielJRaine** [comment]
The code you have above is exactly what I tried before, as is the corrected version.
I will also make a side note that this same solution did not work when using Mirage to mock my my back-end, for whatever reason.

**Comment by jrhorn424** [comment]
Thanks @DanielJRaine!
