### ISSUE TITLE
Bootstrap breaks when deploying to gh-pages (browser-template)

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/capstone-project#342]
Hi, 

My navbar and all css breaks at deployment but looks good in local host. I noticed that on the gh-pages deployment document, it says:

"In your .gitignore file, comment out the lines *bundle.js and dependencies.js so git no longer ignores those files e.g., # *bundle.js. Alternatively you can remove those lines altogether."
https://github.com/ga-wdi-boston/gh-pages-deployment-guide

I did not have dependencies.js. That's about it.

Any suggestions are appreciated!
V

**Comment by viohlet** [comment]
I see an error when I inspect the deployed site:

```
GET https://viohlet.github.io/microwave-wars-client/vendor.bundle.js    404 (Not Found)

Uncaught ReferenceError: webpackJson is not defined @ bundle.js:1

```

I also found an issue that might explain this but I am not 100% positive.
[https://github.com/ga-wdi-boston/browser-template/issues/61](url)

**Comment by raq929** [comment]
Did you run grunt build after commenting the .gitignore?

**Comment by viohlet** [comment]
Hi @raq929 ! Thanks for the speedy reply. I did run grunt build after commenting the .gitignore as it says in step 4 of the deployment guide too. There was no dependencies.js file though, so only deleted the *bundle.js

**Comment by payne-chris-r** [comment]
Have you looked through closed issues?

**Comment by jrhorn424** [comment]
1. make these changes: https://github.com/ga-wdi-boston/browser-template/commit/557a0c1d9ae981b11903ffcf13f775acbe58e616
2. follow the most recent guide: https://github.com/ga-wdi-boston/gh-pages-deployment-guide

@ga-wdi-boston/core The issue was @viohlet downloaded the template before GitHub broke last week; that is, she downloaded the template a week ago, then GitHub broke our deployments the next day. She followed the guide without realizing changes has been made to the template after she downloaded it.
