### ISSUE TITLE
Re-do Project 2 Requirements

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/capstone-project#345]
We don't have specific requirements for people that want to re-do project 2.

**Comment by jrhorn424** [comment]
We have had the following requirements for about a year. Usually, folks ask about their projects and meet of us. We tell them this:
- You may redo your second project.
- In order to meet requirements, your new full-stack app must have a new feature.
- The client must be in Ember. Ember is not required if you do not re-do your second project.
- A re-used API must have one new resource and one new relationship.

cc @gaand
