### ISSUE TITLE
using youtube and Web Audio API

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/capstone-project#347]
HI -- I'd like to use a couple of third party APIs in my capstone. For youtube, I found an ember package that's pretty awesome as far as getting players to appear and run, but if you want to customize controls, they want you to build an object in the controller, which of course my app doesn't have. I'm also considering just using the youtube api directly (which I would also need help with) since it looks like there's more customization available. Here's the npm package:

https://www.npmjs.com/package/ember-youtube

and the youtube api:

https://developers.google.com/youtube/iframe_api_reference

I'm also hoping to use Web Audio API, which is here: 

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

I haven't played with it yet, but I'm anticipating having similar problems. I managed to find an ember implementation, but it also uses controllers. 

Can you help me get started with these things? They look like fun (and a lot of work :) )Thanks!

**Comment by raq929** [comment]
So, we're not teaching them, because they are eventually going away, but there's nothing preventing you from using controllers, as they are still supported. You can use the same format to generate them: `ember g controller <name>`. 
If you do want to avoid them entirely, then most of the code you're finding for the controller can probably go in a component. I might try that method first, and if it doesn't seem like it's getting you anywhere, scrap it and just use controllers. 

If I were you, I would take some time (a *clearly defined* amount of time) to play around with these things. Which one suits your purpose best? Which is easiest to implement? What is best as a stretch goal? 

@jrhorn424 is wise in the ways of Ember, though, and may have some other ideas for you?

**Comment by ioncrash** [comment]
Cook thanks. I just remembered also, I noticed that when I did npm install ember-youtube,  it put the template and component in node-packages, rather than the app folder... Should I generate a new component? Or try to modify the one the node_packages?

**Comment by raq929** [comment]
You can't modify your node_modules, because you're not committing them, so any changes you make will be lost when you deploy. It looks like (from the docs) you can just plug it in whereever you want to use it.

**Comment by raq929** [comment]
(If that doesn't work - try the simplest case first - then we can explore other options.)

**Comment by ioncrash** [comment]
Closing this issue for now... Apparently the ember install just put the component and template files in node_modules incorrectly. So I just generated a new component and then copied over the contents
