### ISSUE TITLE
Issues with create

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/capstone-project#36]
When clicking on create getting error, the token is being passed but the object is not. 

('#create-credentials').on('click', function(e) {
    var credentials = wrap('credential', form2object(this));
    var credentials = form2object(e.target);
    var token = PasswordApp.token;
    e.preventDefault();
whatsMyPassword.createPasswords(token, credentials, callback); token = "d573a6666f82b476f0b99188fd2d6c03", credentials = Object {}
    });

**Comment by jrhorn424** [comment]
Please use backticks to paste code.

It isn't clear here what the error is.

Is this actually inside your function? 

```
whatsMyPassword.createPasswords(token, credentials, callback); token = "d573a6666f82b476f0b99188fd2d6c03", credentials = Object {}
```

`Object {}` should be a syntax error.

I will help you debug this after you fix linter warnings, if there are any.

**Comment by pguzman26** [comment]
```
$('#create-credentials').on('click', function(e) {
    var credentials = wrap('credential', form2object(this));
    var token = PasswordApp.token;
    e.preventDefault();
    whatsMyPassword.createPasswords(token, credentials, callback);
    });
```

**Comment by pguzman26** [comment]
there we go

**Comment by pguzman26** [comment]
Hey Jeff,

```
token = "d573a6666f82b476f0b99188fd2d6c03", credentials = Object {}
Object {}
```

Is what shows up when I put a break point. Sorry for the confusion.

**Comment by jrhorn424** [comment]
Inside your function, do `console.log(form2object(this));`. What do you see?

**Comment by jrhorn424** [comment]
See #26 as well.

**Comment by jrhorn424** [comment]
Several issues:
1. `form2object` was fine.
2. `form2object` was being called inside a click handler attached to a button, instead of inside a submission handler attached to a form.
3. The submit button was a `<button>` instead of `<input type="submit">`
4. All inputs were un-named, so no keys were found by `form2object`. That is, `<input type="text">` instead of `<input type="text" name="website">`. All inputs need names in order for `form2object` to work.
