### ISSUE TITLE
Ember issues connecting to Back end

### ISSUE THREAD

**Issue by Sphilippe7** [ga-wdi-boston/capstone-project#374]
I've gone down the list and followed the ember resources repo but I'm having problems viewing pictures or any other content when clicking on my list of photos.

The message in my console says:
Encountered "0" in payload, but no model was found for model name "0" (resolved model name using rate-my-photos@serializer:application:.modelNameFromPayloadKey("0"))

**Comment by raq929** [comment]
This is similar to Alex's issue #371. I'm going to respond to a different issue and come back to it. But what's probably happening is that your backend is not sending the data correctly. 
It should send a list of examples as { 'examples': [] }
What happens when you make a curl GET request to 'photos/' ?

**Comment by Sphilippe7** [comment]
attempting to do one now

**Comment by Sphilippe7** [comment]
Tried it a couple of times and got errors

**Comment by Sphilippe7** [comment]
So after going through it with @raq929 , we determined that the problem was with my serializer. I created a serializer with all the attributes and then had to restart the server. That is a key part to this. You must RESTART YOUR SERVER or else it will not work!
