### ISSUE TITLE
issue with requirement to ensure links are image

### ISSUE THREAD

**Issue by treep78** [ga-wdi-boston/capstone-project#465]
Chris gave me this requirement for my project

" Currently, users can add any text into a link in order to "create a portfolio image." If you look at your app currently, you will see two portfolio images that render broken img links. You need to either validate that a user has entered an img url (ending in .png, .jpeg, .gif, etc.) before allowing the create to succeed, or display it differently if they haven't provided a link that ends in one of those. Please complete this and resubmit before 5pm in order to meet requirements for the capstone project. "

However, many image links to not end in .jpg, or png, or in fact anything of the sort. I have found no method that would allow me to determine if the required link is an image.

**Comment by raq929** [comment]
You can choose which types of images your app will accept. Make an executive decision about which ones you want and validate for those.

**Comment by payne-chris-r** [comment]
What Rachel said. Even if it's only 2-3 types. Talk to Matt Sommers (@callmelife) if you're looking for creative ways to solve this problem. He may be able to point you in the right direction.

**Comment by treep78** [comment]
But I'm not storing images, I storing image URLS, most of them look like this
```
https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/14705640_348763232125121_7810948108183276048_n.png?oh=bdf2466d24947093f2e1ffe3061a16c3&oe=591DA91C
```

**Comment by raq929** [comment]
Some sort of validation is necessary. If you want to validate based on the content-type that you get back from the URL, that's fine, but much more complicated and fraught with security risks.  I think what we're suggesting, although imperfect, is much simpler to implement, and would validate the URL in your example. 
It is a convention that URLs that return images end with .PNG, .JPEG, etc. In your example, you simply chop off the query to see what it ends with.

This requirement is not open for discussion. You must do what we're asking you to in order to complete the project. You don't have to think it's reasonable, but you do have to do it.

**Comment by treep78** [comment]
SOLUTION:
```
      let image = this.get('image');
      let link = image.get('link').split('');
      for(let i=0; i<link.length;i++) {
        if(link[i] === '.'){
          let ext = link[i+1]+link[i+2]+link[i+3];
          if(ext === 'png' || ext === 'jpg') {
            this.sendAction('save', this.get('image'));
            return
          }
        }
      }
      this.get('image').setProperties({link: 'This field must be a link to a .PNG or .JPG'});
```
