### ISSUE TITLE
One on one request about caching

### ISSUE THREAD

**Issue by alexkarasik** [ga-wdi-boston/capstone-project#579]
I was told to do caching for the extra credit on my project and I want to talk about what is and understand it better at some point today. I am not sure how to implement it and want to attempt it.

**Comment by bernardlee** [comment]
What have you read about caching?  What is your current understanding of what caching is and how it works?

**Comment by alexkarasik** [comment]
Caching stores content generated from a request-response cycle and reuses similar sets of data when responding to similar requests so the database does not have to make a duplicate request, but can just grab the matching data that is already stored in the database. Its purpose is to boost an application's performance and I can implement it with a memory hash called Redis, but I am not sure how to do this.

**Comment by raq929** [comment]
There's pretty extensive documentation: https://redis.io/documentationhttps://redis.io/documentation

Do you have a specific question about implementation?
What have you tried?

**Comment by jrhorn424** [comment]
@alexkarasik You may have made a strategic error by not responding to @raq929's questions before jumping into a redis tutorial. I'm not sure how much time you spent researching redis, so maybe it was no big deal.

@raq929 I consulted @alexkarasik over lunch to drop Redis, because the discussed "cacheing" requirement I asked him to implement was:

1. check if there exists a record in your API matching a record in the third-party API
    1. if not, save a copy of the record in your API
    1. if so, bypass the GET request for the record from the third-party API and instead serve the record from your own database.

Additionally, if that was completed, he could then pursue something more complex, such as interval-cacheing and expiry.

**Comment by alexkarasik** [comment]
Thank you for that Jeff. I only spent about 30 minutes on it, but am still working on meeting the basic requirements. I will get back to caching in a few hours hopefully when I figure the rest of this stuff out, but I think I conceptually understand what you are saying and will research implementing it  at around 6.
