### ISSUE TITLE
Request to review my project scope 

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/capstone-project#6]
I changed my Proj 4 app concept on Friday and put together the new data model, relationships and all of the user stories. Before I get too deep in developing this, I would like an instructor to review it with me.

**Comment by jrhorn424** [comment]
Would you mind sharing your user stories and relational model?

**Comment by LaurisaNeuwirth** [comment]
sure they are in my trello. If I add your email there is that easy enough for you to access it?

**Comment by LaurisaNeuwirth** [comment]
My trello is now public: https://trello.com/b/3uf6rrY6/freshex-find-outdoor-exercise-classes

**Comment by jrhorn424** [comment]
I like the scope and order of your user stories (I'm assuming you've prioritized them, most important at the top?).

`An event: has many registrants / has many reviews / has one teacher`. This seems to imply a relationship with at least two models. I'd have an event belong_to a teacher, putting the teacher_id (through class User) on the event table. I think it's correct to say an event has_many registrants, as long as it is through a join table with User, since Users will have many registrations as well.

`A user has many classes / has many reviews` I'm comfortable with this. Maybe has_many registrations is better, since a user could also teach a class? Users are related to classes in two ways: through teaching it or through attending it, implying two relationships between the same classes. This means you'll need to have a look at using "class name" and perhaps "foreign key" options in active record association methods.

Notes from your ERD (maybe repeated above): any time you have a many-to-many, include a named join table. So, by your drawing, you need a join table between User and Event. The rest of your ERD is incomplete. How are the other entities related (Signups and Reviews)? ERDs are easier to change than tables, so I want to make sure you've got that outlined well.

Lastly: be consistent with names. Are events and classes different? Signups and registrations?

**Comment by LaurisaNeuwirth** [comment]
Thanks for your input, Since there is a lot to cover there, is it possible to go thru this in person?

**Comment by jrhorn424** [comment]
Sure, come find me in classroom 1. I think I've given you the green light and noted my concerns, but if you have questions we can chat.
