### ISSUE TITLE
grunt deployed failed, now stuck in github hell

### ISSUE THREAD

**Issue by octater** [ga-wdi-boston/capstone-project#644]

**Comment by octater** [comment]
ran a grunt deploy and it got stuck.  Nothing ever can back.  I did a ctrl-c and now I am stuck in branch ~/wdi/dirt-napstr-client (gh-pages) not knowing what to do next.  I cannot change to back to master and cannot delete gh-pages branch.

**Comment by BenGitsCode** [comment]
Hey Terry. What does `git status` tell you?

**Comment by octater** [comment]
~/wdi/dirt-napstr-client (gh-pages)
$ git status
On branch gh-pages
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.editorconfig
	.eslintrc.json
	.gitignore
	.jscsrc
	.jshintignore
	.jshintrc
	.remarkrc
	.scss-lint.yml
	CONTRIBUTING.md
	Gruntfile.js
	LICENSE
	README.md
	STYLE.md
	assets/
	forms.md
	grunt/
	images/
	index.js
	lib/
	package-lock.json
	package.json
	spec/

nothing added to commit but untracked files present (use "git add" to track)
~/wdi/dirt-napstr-client (gh-pages)
$ 


I never had a branch named gh-pages???

**Comment by BenGitsCode** [comment]
so here's a better sense of what's happening to start:

When you run `grunt deploy` it runs these commands all in order--if any single one fails it stops right at that step. 

```js
  'git-is-clean': {
    // `$(git status --porcelain)` will evaluate to the empty string if the
    // working directory is clean.
    // `test -z` will exit 0 (true) if its argument is an empty string.
    // If it doesn't exit true, `(git status && false)` will show why the
    // repository isn't clean and exit false causing the grunt tasks to end.
    command: 'test -z "$(git status --porcelain)"  || (git status && false)'
  },
  'git-push-master': {
    command: 'git push origin master'
  },
  'git-checkout-master': {
    command: 'git checkout master'
  },
  'deploy-prepare': {
    command: [
      'git branch -D gh-pages || echo "so not removed"',
      'git checkout --orphan gh-pages',
      'git rm --cached \'*\''
    ].join(' && ')
  },
  'deploy-publish': {
    command: [
      'touch .nojekyll',
      `git add --force .nojekyll ${ghPagesList}`,
      'git commit -m "deploy task"',
      'git push origin gh-pages --force',
      'git clean -x -d --force --exclude=node_modules',
      'git checkout master'
    ].join(' && ')
  }
}
```

It looks like yours broke somewhere _after_ creating gh pages with `git checkout --orphan gh-pages`

but before finishing publishing to gh-pages. 

The reason you're `stuck` is because it was in the middle of adding all of those files (untracked by git at the moment) when it broke. 

try this for me: run `git clean -x -d --force --exclude=node_modules`
`git status` *if status is clean* `git checkout master` `git push origin master` and then try `grunt deploy` again.


I'm on my way home now but I'll check this  when I'm back to my computer. 

You've got this.

**Comment by octater** [comment]
I ran git clean -x -d --force --exclude=node_modules
then did a git status:

$ git status
On branch gh-pages
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	node_modules/

nothing added to commit but untracked files present (use "git add" to track)
~/wdi/dirt-napstr-client (gh-pages)
$ 

looks like node_modules/ is still there

**Comment by octater** [comment]
Thanks Ben.  The commands worked after running npm install.  Finishing up the README files now.
