### ISSUE TITLE
Guidance deciding whether my concert table needs a belongs to user relationship 

### ISSUE THREAD

**Issue by MarcyNash** [ga-wdi-boston/capstone-project#757]
My concert table is a list of all available concerts in the Boston area. 

I didn't want to touch the user table, so I created a profile table which belongs to a user. 
``` User Table    -|-----<   A profile has one user ```  User Table has_many profiles.

I originally set up the concert table like the profile table and now I'm having second thoughts about this decision
``` User Table    -|-----<   A concert has one user ```  User Table has many concerts.

Currently, I'm populating the table with a csv file I created. The table is not editable; only CRUD actions are INDEX and SHOW. In the the future, the concert table will be populated once a week or once a month by web crawler getting and parsing concert data from websites. When I'm using the web crawlers for data I'll also need DESTROY. Sounds like I'll need and administrator at that point in time, but enough about the future :-)

So that said, I'm about to set up a join table between the concert table and the profile table.
``` Profile Table ->------<- Profile_Concert Join Table ```
``` A profile has many concerts and a concert has many profiles```

1. If the concert table has no associations, will I have trouble creating the above join table?
2. Have I just violated a best practice by having a table with no associations?

Thanks!

**Comment by scottyscripts** [comment]
1) you should not run into any issues if concerts table doesn't contain references. Each entry in your join table will end up having a reference to a profile (`profile_id`) and a reference to a concert (`concert_id`) So that is how `profile` and `concert` will know about each other
2) No violation here! This is a common scenario when using join tables. Check out this entry in rails docs that I constantly reference. http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by MarcyNash** [comment]
Thanks Scott!
